server:
  port: 8001

spring:
  application:
    name: cloud-alibaba-nacos-provider
  cloud:
    #配置nacos的服务地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
